# usando chave descomplicando_kubernetes
# dckr_pat_YvNX_khbx2CraxdvxFjzaNy_ZMA
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-gpc
type: kubernetes.io/dockerconfigjson

# gerado a partir do ~/.docker/config.json que é gerado após o comando:
# docker login -u gupoco -p dckr_pat_YvNX_khbx2CraxdvxFjzaNy_ZMA
# esse ~/.docker/config.json está em codificação binária base64. Fiz isso pelo comando:
# base64 /home/gpc/.docker/config.json
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlozVndiMk52T21SamEzSmZjR0YwWDFsMlRsaGZhMmhpZURKRGNtRjRaSFo0Um1wNllVNTVYMXBOUVE9PSIKCQl9Cgl9Cn0=
