apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  containers:
  - name: webserver
    image: nginx:1.20
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
      - containerPort: 443
    volumeMounts:
      - name: nginx-conf-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      
      - name: nginx-tls
        mountPath: /etc/nginx/tls
  volumes:
    - name: nginx-conf-volume
      configMap:
        name: nginx-configmap
    - name: nginx-tls
      secret:
        secretName: webserver-tls
        items:
          - key: tls.crt
            path: certificado.crt
          - key: tls.key
            path: chave-privada.key