apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: local-lb
spec:
  containers:
  - name: myapp
    image: nginx:1.15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
