## O Jefferson faz com NFS, não consegui adaptar para local e estou dando andamento ao curso.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: frigideira
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"